;/*FB_PKG_DELIM*/

__d("CometComposerMediaAttachmentAreaResource",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a=c("JSResourceForInteraction")("CometComposerMediaAttachmentArea.react").__setRef("CometComposerMediaAttachmentAreaResource");b=a;g["default"]=b}),98);
__d("EventCometActionContextDefault",[],(function(a,b,c,d,e,f){"use strict";a={event_action_history:[]};f["default"]=a}),66);
__d("EventCometActionContext",["EventCometActionContextDefault","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(c("EventCometActionContextDefault"));g["default"]=b}),98);
__d("EventCometActionLoggerUtils",["CometRouteURL"],(function(a,b,c,d,e,f,g){"use strict";var h={mechanism:"unknown",surface:"unknown"},i=3;function a(a,b){var c=[].concat(a.event_action_history||[]);c.length>=i&&(c=c.slice(c.length-i+1));var d=j(a);c.push({event_tracking:d.event_tracking,extra_data:d.extra_data,mechanism:b.mechanism,surface:b.surface});return babelHelpers["extends"]({},a,{event_action_history:c})}function j(a){a=a.event_action_history;if(a==null||a[a.length-1]==null)return h;return a.length>=2?a[a.length-2]:a[a.length-1]}function b(){var a=d("CometRouteURL").useRouteURL(),b=/\/events\/\d+/;if(b.test(a))return"permalink";if(a.includes("/events/calendar"))return"bookmark_calendar";if(a.includes("/events"))return"bookmark";return a.includes("profile.php")?"timeline":"newsfeed"}g.createForNewSurface=a;g.getLastActionHistoryEntry=j;g.useExtractEventComposerSurface=b}),98);
__d("useEventActionLoggerParams",["CometRouteParams","EventCometActionLoggerUtils","react","recoverableViolation","useRouteReferrer"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useMemo,j={event_action_history:[]};function k(a,b,c){var e,f=typeof a.acontext==="string"?a.acontext:null,g=typeof a.notif_t==="string"?a.notif_t:null;f=l(f);if(!((e=f.event_action_history)==null?void 0:e.length)){e=o(a,c);e&&(f=babelHelpers["extends"]({},f,{event_action_history:[{surface:e}]}))}f.ref_notif_type=(a=f.ref_notif_type)!=null?a:g;c=d("EventCometActionLoggerUtils").createForNewSurface(f,b);return[f,c]}function l(a){if(a==null||a==="")return j;var b=null;try{b=JSON.parse(a)}catch(a){c("recoverableViolation")("Unable to parse action_context string"+a.toString(),"events")}if(b==null)return j;a=b;b=a.action_history;var d=a.event_action_history,e=a.ref,f=a.ref_notif_type;a=a.source;d=(d=d)!=null?d:b;b=[];typeof d==="string"?b=p(d):Array.isArray(d)&&(b=q(d));return{event_action_history:b,ref:e,ref_notif_type:f,source:a}}var m=["google","bing","yahoo"],n={app:"home",gaming:"games_feed",group:"group",groups:"group",marketplace:"marketplace",page:"page",profile:"user_timeline",save:"saved_dashboard",search_results:"search",watch:"video_feed"};function o(a,b){if(a.ref==="notif"||a.notif_id!=null)return"notifications_tab";b=b==null?void 0:b.split(".");b=b!=null&&b.length>=2&&b[0]==="comet"?b[1]:null;if(b!=null&&Object.prototype.hasOwnProperty.call(n,b))return n[b];if(a.ref==="newsfeed")return"newsfeed";b=(b=document.referrer)==null?void 0:(a=b.match(/\/\/[^\/]*?([\w-]+)\.\w+(\/|$)/))==null?void 0:a[1];if(b!=null){if(m.includes(b))return"external_search_engine";if(b!=="facebook")return"external"}return null}function p(a){if(a==="")return[];var b=[];try{b=JSON.parse(a)}catch(a){c("recoverableViolation")("Unable to parse action_history string"+a.toString(),"events");return b}return q(b)}function q(a){return!Array.isArray(a)?[]:a.filter(function(a){return typeof a==="object"}).map(function(a){var b=a.event_tracking,c=a.extra_data,d=a.mechanism;a=a.surface;return{event_tracking:typeof b==="string"?b:void 0,extra_data:typeof c==="object"?JSON.stringify(c):"",mechanism:typeof d==="string"?d:"unknown",surface:typeof a==="string"?a:"unknown"}})}function a(a){var b=d("CometRouteParams").useRouteParams(),e=c("useRouteReferrer")();return i(function(){return k(b,a,e==null?void 0:e.tracePolicy)},[b,a,e==null?void 0:e.tracePolicy])}g["default"]=a}),98);
__d("useEventCometActionContext",["EventCometActionContext","EventCometActionContextDefault","react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useContext;function a(){var a=i(c("EventCometActionContext"));a===c("EventCometActionContextDefault")&&c("recoverableViolation")("EventCometActionContext used without provider","events");return a}g["default"]=a}),98);
__d("UnifiedShareSheetDialogContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b={LSresults:[],isShareSheetEntrypoint:!1,setShouldHideMessengerSection:function(a){},setShouldHideShareToSection:function(a){}};c=a.createContext(b);g["default"]=c}),98);
__d("CometEventPermalinkTab",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({ABOUT:"about",DISCUSSION:"discussion",BRACKETS:"brackets",BROADCASTS:"broadcasts",PARTICIPANTS:"participants",STANDINGS:"standings",VIDEOS:"videos",PAID_ACCESS:"paid_access"});c=a;f["default"]=c}),66);
__d("XCometEventCreateControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/create/",Object.freeze({default_is_online:!1,default_is_paid_online_event:!1,dialog_entry_point:"others",should_skip_format_step:!1}),void 0);b=a;g["default"]=b}),98);
__d("XCometEventPermalinkControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/{event_id}/{?child_event_id}/",Object.freeze({active_tab:"about",show_created_event_toast:!1,hide_invite_flow_filter_groups:!1}),void 0);b=a;g["default"]=b}),98);